//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATeamRPG
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ATeamDB : DbContext
    {
        public ATeamDB()
            : base("name=ATeamDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Cell> Cell { get; set; }
        public virtual DbSet<Map> Map { get; set; }
        public virtual DbSet<Player> Player { get; set; }
        public virtual DbSet<Stat> Stat { get; set; }
    }
}
