//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATeamRPG
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cell
    {
        public int MapId { get; set; }
        public int X { get; set; }
        public int Y { get; set; }
        public Nullable<int> PlayerId { get; set; }
        public int Gold { get; set; }
        public byte IsGround { get; set; }
    
        public virtual Map Map { get; set; }
        public virtual Player Player { get; set; }
    }
}
